WIP #156 Configuração Sentry
Eccoar/2020.2-Eccoar_Mailer pull request #10
Opened 2021-04-16 13:58 UTC by MatheusBlanco

## Conteúdo
Foi configurado o sentry.io para que se pudesse capturar erros de requisição, monitorar performance e enviar alertas em ambiente de produção

Neste pull request se realizou:
- Adição de sentry no express
- Configuração do dashboard
- Configuração de alertas

## Checklist

- [X] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [X] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [X] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [X] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [X] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [X] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [X] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-17 22:31 UTC, devsalula requested changes
Da uma olhadinha no que eu pedi.
Olha nos outros repos tbm, pfvr.
Uma dúvida, como eu testo? E quais são as variáveis que preciso passar para o teste? Pode me passar no privado?

2021-04-17 22:31 UTC, devsalula commented on src/server.ts
> +	'https://d963df56f6dc4879a92cbdfd113f7fcf@o570893.ingest.sentry.io/5718329';
Esse link pode ficar exposto assim?

2021-04-17 22:31 UTC, devsalula commented on src/server.ts
> +app.use(
Não coloca as funções dentro do ```app.user``` dessa forma não, pfvr.
Tenta atribuir a uma variável e passe a variável para elas.
A mesma coisa para a linha 26 e 27.

2021-04-17 23:26 UTC, MatheusBlanco commented
> Da uma olhadinha no que eu pedi.
> Olha nos outros repos tbm, pfvr.
> Uma dúvida, como eu testo? E quais são as variáveis que preciso passar para o teste? Pode me passar no privado?

To olhando aqui agora msm. Pra testar é só fazer requisições que vão quebrar. Umas coisas que eu tava fazendo era dar down -v no docker de complaints e subir ele a primeira vez. No gateway eu consegui capturar erros 400 e aí é só enviar requisições quebradas. Em mailer eu testei aquela quebra que acontece na fila do redis também.
A única variável é a key do sentry pra nossa conta. Vou te passa

2021-04-19 22:38 UTC, devsalula approved these changes

2021-04-19 22:38 UTC, devsalula commented
Bom trabalho @MatheusBlanco !! 🚀

2021-04-27 01:21 UTC, Victor-Buendia approved these changes

2021-04-27 01:22 UTC, merged